### ISSUE TITLE
Should toml be added as a dependency?

### ISSUE THREAD

**Issue by max-sixty** [keewis/blackdoc#100]
Hi @keewis !

Our CI is failing with:

```
  File "/root/.cache/pre-commit/repon4ojay_j/py_env-python3/lib/python3.8/site-packages/blackdoc/blackcompat.py", line 9, in <module>
116    import toml
```

And I noticed that toml isn't specified in setup.cfg. Should it be?

Thank you!

**Comment by keewis** [comment]
yes, I did miss that. Obviously, if we're using it in some part of the code it should be a dependency. Do you want to send in a PR?

As for the reason why it didn't fail before: `blackdoc` depends on `black`, which used to depend on `toml` but recently switched to `tomli` (the reason I think was that `toml` has a "lack of maintainership" issue). Given that the code that uses `toml` is vendored, I think I'll copy the most recent version from `black` and switch to using `tomli` when I get the time. I'm not quite sure when that will be so I'll issue a bugfix release with the `setup.cfg` update.

**Comment by max-sixty** [comment]
Yes. I need per-repo approval to contribute to repos, and blackdoc is not yet on that list. It won't be hard to get but takes a few days — as long as that timing is OK with you

**Comment by keewis** [comment]
well, I'd estimate this to be a single line PR so if getting the approval takes more than 5 Minutes it's probably not worth it. Unless you expect to open other PRs? (to be sure, those are always welcome!)

**Comment by keewis** [comment]
reopening so I don't forget to update the vendored code
