### ISSUE TITLE
btw

### ISSUE THREAD

**Issue by asottile** [keewis/blackdoc#103]
https://github.com/asottile/blacken-docs

**Comment by keewis** [comment]
Thanks for the link, @asottile. I'm aware of that project, but I didn't find out about it until after I had written this, and even then it didn't support doctest for quite some time.

Both projects are also not completely the same: when implementing `blackdoc` I made some design choices that allow certain features `blacken-docs` doesn't have (some intentionally), e.g.  `--check` and `--diff`. Of course, the same is true for `blackdoc` (`markdown` support is missing, for example).

I'll close this for now but will keep an eye on `blacken-docs`.

**Comment by MarcoGorelli** [comment]
The projects look different, anyway:

- `blacken-docs` works on Python _snippets_ in non-Python files (e.g. `rst`)
- `blackdoc` works on doctests in Python files

**Comment by asottile** [comment]
blacken-docs can also do python files
