### ISSUE TITLE
Would it be possible to only write files on changes?

### ISSUE THREAD

**Issue by max-sixty** [keewis/blackdoc#127]
Often I run something like `watchexec -- {some tests}`. Including `blackdoc` in those tests causes this to loop forever, because it seems `blackdoc` writes to files even when it doesn't change them.

To the extent this would be an easy change, this would be great! (but also maybe it's just me and so no need to make changes in that case)

**Comment by keewis** [comment]
I thought that's what it already does, but apparently that's not true: https://github.com/keewis/blackdoc/blob/5049a7f97ebe59bd82a8b1b0bb1b5d729bb8cb1d/blackdoc/__main__.py#L37-L44 The fix would indeed be very simple...
