### ISSUE TITLE
multiple semicolon separated commands are not handled well

### ISSUE THREAD

**Issue by jugmac00** [keewis/blackdoc#143]
```
>>> print("----");print(anon_browser.contents)
```

gets turned into

```
>>> print("----")
... print(anon_browser.contents)
```

When I then tried to run the doctests I got a
```
SyntaxError: multiple statements found while compiling a single statement
```

**Comment by keewis** [comment]
this is not actually hard to do (and even easier after #144). However, we'd need to analyze the AST to implement it, which up until now that left entirely to `black`. Let me see what I can do.

**Comment by jugmac00** [comment]
@keewis For now, as a workaround, I converted the above statements into a single one.

```
-    >>> print("----")
--
+   >>> print("----\n%s" % anon_browser.contents)
```

**Comment by keewis** [comment]
this will be fixed in the next version, but you could also just pass both to a single `print` call:
```python
>>> print("----", anon_browser.contents, sep="\n")
```
which is probably better, given that splitting the `print` calls into separate doctest lines makes the `----` a bit pointless?

**Comment by jugmac00** [comment]
Indeed. 👍
