### ISSUE TITLE
use format parsing libraries instead of custom line based parsing

### ISSUE THREAD

**Issue by keewis** [keewis/blackdoc#32]
Right now `blackdoc` goes through the lines one by one, tries to extract code, format the code using black, then put everything back together. While this does work, extending to different file formats becomes difficult, especially when trying to extend to jupyter notebooks (json files).

There are a lot of libraries for parsing the currently supported formats (or the planned formats):

- [`docutils`](https://docutils.sourceforge.io/docs/) for parsing restructured text (`rst`)
- [`ipython sphinx extension`](https://github.com/ipython/ipython/tree/master/IPython/sphinxext) / [`jupyter sphinx extension`](https://github.com/jupyter/jupyter-sphinx) for reading ipython / jupyter styled code blocks
- [`markdown-it-py`](https://github.com/executablebooks/markdown-it-py) for markdown
- [`doctest`](https://docs.python.org/3/library/doctest.html) for extracting doctest lines
- [`json`](https://docs.python.org/3/library/doctest.html) for parsing jupyter notebooks

this might come with the disadvantage of slower reading since e.g. `docutils` does more than just reading code blocks, but using those might make the tool a bit more robust and easier to extend to new formats. Another disadvantage is that right now we're reading the files only once but we might have to read at least docstrings more often (that is if we don't restrict python files to doctest -- should be possible, rst in docstrings is rare).

**Comment by keewis** [comment]
thinking about this again, maybe we don't have to do that? There's lots of utilities that apply `black` to notebooks, so we don't have to add that. `markdown` support would be nice, but that should be somewhat similar to `rst` support. We're also reading files only once: every line is classified and the appropriate extraction / reformatting functions are called, in sequence.

**Comment by keewis** [comment]
since those libraries are fundamentally different from how the tool currently work (especially `docutils`), using those would require a rewrite, which I'm not prepared to do (and the main motivation, notebook support, can be done using other tools, e.g. `nbQA`).

Instead, `markdown` support will have to be implemented in a new `blackdoc.formats` module.

**Comment by MarcoGorelli** [comment]
> the main motivation, notebook support, can be done using other tools, e.g. nbQA

Just FYI - hopefully, soon, this won't even require extra tools https://github.com/psf/black/pull/2357
