### ISSUE TITLE
Publish the package to the conda-forge channel

### ISSUE THREAD

**Issue by seisman** [keewis/blackdoc#42]
Could you publish the package to the [conda-forge channel](https://conda-forge.org/) so that users can install the package via `conda install blackdoc`? Thanks.

**Comment by keewis** [comment]
see conda-forge/staged-recipes#12705

**Comment by keewis** [comment]
the staged recipe has been merged so we only have to wait until the feedstock was created and the packages are built, which hopefully is a automatic process.

**Comment by keewis** [comment]
the package is available now
