### ISSUE TITLE
Support `--diff` option

### ISSUE THREAD

**Issue by HideakiImamura** [keewis/blackdoc#53]
Thanks for the great project! [Recently](https://github.com/optuna/optuna/pull/1958), [Optuna](https://optuna.org/), which is a hyperparameter optimization framework, has started to use the blackdoc in CI.

The `black` supports the `--diff` option to show the difference before and after formatting. This option is enabled in the CI of Optuna. However, `blackdoc` does not. This option is useful for PR authors to find out why CI has failed. I would love to have blackdoc support this option.

**Comment by keewis** [comment]
this has been on my roadmap for quite some time now (see points 4 and 5 in https://github.com/keewis/blackdoc/issues/33#issuecomment-700330810).

Note to self: use [`difflib.unified_diff`](https://docs.python.org/3/library/difflib.html#difflib.unified_diff)
